name: Publish NuGet package

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Pack
      working-directory: Source/Tazor
      run: dotnet pack
    - name: Publish
      working-directory: Source/Tazor/bin/Release
      run: dotnet nuget push "bin/Release/Tazor.*.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source "github"
    
